name: Ping Website Every 20 Minutes

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the website
        run: |
          curl -I -m 30 -L https://defensive-glori-larsmartens-4c10bcc4.koyeb.app/
